version: '3.8'

# Services
services:
    # Go Service
    go:
        build:
            dockerfile: ./deployment/local/go/go.dockerfile
        container_name: pushrrr-go
        stdin_open: true
        tty: true
        volumes:
            # - './app:/app'
            - './app:/app'
            - './data:/data'
        ports:
            - 9000:9000
        networks: 
            - backend    
        # depends_on:
        #     - sqlite
        # command: go run main.go
        # need to reload supervisor after rebuild WIPPPPPPPPPPPP 
        # develop:
            # watch:
            #     - action: sync+restart
            #       path: ./app
            #       target: ./build
                    # - path: ./app
                    # - target: ./app


    # Nginx Service
    nginx:
        build: 
            dockerfile: ./deployment/local/nginx/nginx.dockerfile
        container_name: pushrrr-nginx
        ports:
            - 8484:80
        links:
            - 'go'
        volumes:
            - './deployment/local/nginx/conf.d:/etc/nginx/conf.d'
            - './deployment/local/nginx/:/var/log/nginx'
            # - './build:/var/www/html'
        networks: 
            - backend        
        depends_on:
            - go
    mariadb:
        build:
            dockerfile: ./deployment/local/mariadb/mariadb.dockerfile
        container_name: pushrrr-mariadb
        restart: always
        stdin_open: true
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: pushrrr
            MYSQL_PASSWORD: pushrrr
            MYSQL_DATABASE: pushrrr
        ports:
            - 3366:3306
        volumes:
            - ./database/mariadb/data:/var/lib/mysql
        networks: 
            - backend

networks:
    backend:
        driver: bridge   
         

    


